### ISSUE TITLE
dexie-react-hooks: `self` is not defined in Next.js

### ISSUE THREAD

**Issue by stutrek** [dfahlander/Dexie.js#1207]
I am trying to use `useLiveQuery` in a next.js app. By default Next will compile and run the code on both the client and server. It's easy to guard against code running on the server, but preventing it from importing code requires dynamic imports, which aren't a good choice for importing React hooks.

It looks like the transpiler adds a `self`, which node can't make any sense of. It's hard to tell because the code in dist is minified instead of only being transpiled.

```
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/.../node_modules/dexie-react-hooks/dist/dexie-react-hooks.js:1:308)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///dexie-react-hooks:1:18)
    at Object.dexie-react-hooks (/Users/.../.next/server/pages/index.js:173:1)
    at __webpack_require__ (/Users/.../.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./pages/index/index.tsx:13:75)
    at Module../pages/index/index.tsx (/Users/.../.next/server/pages/index.js:151:1)
    at __webpack_require__ (/Users/.../.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./pages/index.ts:2:70)
    at Module../pages/index.ts (/Users/.../.next/server/pages/index.js:128:1)
    at __webpack_require__ (/Users/.../.next/server/pages/index.js:23:31)
```

When I wrote the code, my assumption was that it would import without problems, then error if the code is actually called on the server. There could probably be a neat way for it to work with dexie-cloud too.

**Comment by dfahlander** [comment]
Thanks for the report. I'm using webpack to bundle dexie-react-hooks and it seems to be the UMD output that webpack produces that causes this to happen. I'm normally using rollup for libs but tried to use webpack this time. Seems to be [this issue](https://github.com/webpack/webpack/issues/6784). Might need to over to rollupjs to get it fixed.

**Comment by stutrek** [comment]
Cool. Personally, I have given up on using bundlers for libraries and just use `tsc`.

**Comment by shrutikhetanvakt** [comment]
ma getting this issue now ./node_modules/dexie-react-hooks/dist/dexie-react-hooks.mjs 134:13-21
Can't import the named export 'useState' from non EcmaScript module (only default export is available)

**Comment by dfahlander** [comment]
@shrutikhetanvakt Try latest version (1.0.5). It should have been solved there - I was importing named imports from React, which is not really compliant when importing non-ES modules.

**Comment by dfahlander** [comment]
Note: The latest version of dexie-react-hooks (version 1.1.3) gives better nextjs support - no need to dynamically import components or check for SSR within your queries - just use the vanilla react samples and import components normally.
