### ISSUE TITLE
Dexie not working on Internet Explorer 11 - same program works on Firefox/Chrome

### ISSUE THREAD

**Issue by brailateo** [dfahlander/Dexie.js#240]
Tried 1.3.4 and 1.3.6 versions of Dexie, the same result!
The program works perfectly on Firefox/Google Chrome but on Windows/Internet Explorer 11 got errors and documents are not saved.
```
dumpToIndexedDB:  Error: DataError
   at stack (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:187:13)
   at Anonymous function (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:2494:33)
   at doResolve (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:741:13)
   at Promise (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:585:13)
   at Anonymous function (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:2457:25)
   at Promise.newPSD (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:862:13)
   at _promise (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:2453:17)
   at transactionPromiseFactory (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:2400:17)
   at getIDBObjectStore (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:1841:21)
   at add (http://192.168.1.24:5984/aplicatie_cantemir/app/js/lib/dexie.js:2225:21)
```

The program does a clear() all documents from a table, then inserts 713 documents coming from a http stream through jsonpipe , using a compound index for later sorting.
Everything works perfectly on Firefox/Google Chrome!

Promise on Windows/Internet Explorer is done by this polyfill
https://raw.githubusercontent.com/taylorhakes/promise-polyfill/master/promise.js

Any clues?
Thanks for Dexie,
Constantin Teodorescu

**Comment by dfahlander** [comment]
IE lacks support for compound indexes. You could try out my polyfill that tries to bridge that: https://github.com/dfahlander/idb-iegap. Safari has the same issue but the polyfill does not target safari yet.

**Comment by brailateo** [comment]
I changed the compound [prd+ddc+si] index definition and build the table from scratch with a single string  column index that I manually assembled before saving into the database, in order to avoid the compound index.
Got the same error!
Teo

**Comment by dfahlander** [comment]
Yes, it's the wisest thing to do when needing to support IE and Safari - to not use compound indexes but emulate them by concatinating strings. Glad to hear it works!

**Comment by Buwaneka1993** [comment]
@dfahlander  https://github.com/dfahlander/idb-iegap. how do i use this? not clear how do i used with it Dexie.js. any sample code out there ?

**Comment by dfahlander** [comment]
It's actually a bit outdated. I would recommend using IndexedDBShim instead, that also polyfills IE10/IE11 in a similar way. I will update its readme.
