### ISSUE TITLE
Dexie.delete error

### ISSUE THREAD

**Issue by jbvsmo** [dfahlander/Dexie.js#441]
I want to fully wipe a database but the delete function does partial job.
I am using Dexie 1.5.1 and code from here:
https://github.com/dfahlander/Dexie.js/wiki/Dexie.delete()

If I do: `Dexie.delete('MyDatabase');`, the `stackHolder` property of the promise is this:

```
"Error
    at getErrorWithStack (https://unpkg.com/dexie@1.5.1/dist/dexie.js:405:12)
    at new Promise (https://unpkg.com/dexie@1.5.1/dist/dexie.js:786:29)
    at Dexie.delete (https://unpkg.com/dexie@1.5.1/dist/dexie.js:2013:16)
    at Function.delete (https://unpkg.com/dexie@1.5.1/dist/dexie.js:4377:32)
    at <anonymous>:1:13"
```

The data inside each table is deleted, but the database is not removed (E.g. The version is not erased).
I end up with a broken database...

The error seems to be on block starting at line 2013 here: https://unpkg.com/dexie@1.5.1/dist/dexie.js

**Comment by dfahlander** [comment]
Seems like an instability issue of your underlying indexedDB. What browser are you using? Firefox seems to get into an instable state after downgrading an existing browser to an earlier browser version.

**Comment by jbvsmo** [comment]
I restarted the browser and seems like now the delete started working again...
I am using Chrome 55 (latest).

Also is it possible that an open connection to a database from one tab can make the the delete on another tab fail? (Both tabs opened to the same page and using the same database)

**Comment by dfahlander** [comment]
Ok. No, If both tabs are using Dexie, the other tab would close the connection as soon as the deleting tab requests to delete it. This is handled by the version change event and can be overridden to block the deletion. If other page was reloaded for some reason after the deletion, the db might have been recreated with empty tables.

**Comment by jbvsmo** [comment]
That was bugging me... The database had empty tables instead of being fully deleted.
I have code that would run on the populate trigger, so it should not be empty if recreated.

I can't reproduce the error anymore. Feel free to close this ticket if you like.
