### ISSUE TITLE
Joining

### ISSUE THREAD

**Issue by apokalypsi** [dfahlander/Dexie.js#472]
I'm testing the example and it's returning me the following error:

```
Promise
_PSD
:
Object
_lib
:
false
_listeners
:
Array[0]
_numPrev
:
2
_prev
:
Promise
_stackHolder
:
Error at getErrorWithStack (http://localhost:8383/HTML5ApplicationFirebase/dexie.js:321:12) at new Promise (http://localhost:8383/HTML5ApplicationFirebase/dexie.js:732:29) at Promise.then (http://localhost:8383/HTML5ApplicationFirebase/dexie.js:761:22) at Collection._read (http://localhost:8383/HTML5ApplicationFirebase/dexie.js:3496:55) at Collection.toArray (http://localhost:8383/HTML5ApplicationFirebase/dexie.js:3577:29) at getBandsStartingWithA (http://localhost:8383/HTML5ApplicationFirebase/index.html:158:26) at http://localhost:8383/HTML5ApplicationFirebase/index.html:188:25
_state
:
true
_value
:
Array[0]
onuncatched
:
nop()
stack
:
(...)
then
:
(...)
__proto__
:
Promise
_then
:
(onFulfilled, onRejected)
catch
:
(onRejected)
constructor
:
Promise(fn)
finally
:
(onFinally)
stack
:
(...)
then
:
(...)
timeout
:
(ms, msg)
Symbol(Symbol.toStringTag)
:
"Promise"
get stack
:
()
get then
:
()
set then
:
(value)
__proto__
:
Object
```

```
var db = new Dexie('music');
            db.version(1).stores({
                genres: '++id,name',
                albums: '++id,name,year,*tracks',
                bands: '++id,name,*albumIds,genreId'
            });

 function getBandsStartingWithA() {
                // Query
                return db.bands
                        .where('name')
                        .startsWith('A')
                        .toArray(bands => {
                            return Promise.all(bands.map(band =>
                                Promise.all([
                                    db.genres.get(band.genreId),
                                    db.albums.where('id').anyOf(band.albumIds).toArray()
                                ]).then(result => {
                                    // Set genre and albums as direct properties on each result
                                    [band.genre, band.albums] = result;
                                    return band;
                                })
                            ));
                        });
}

```

**Comment by dfahlander** [comment]
The value you see is an instance of Dexie.Promise. To view the result you need to call `.then()` upon it

```js
getBandsStartingWithA().then(result => {
    console.table(result);
});
```

**Comment by apokalypsi** [comment]
It worked, thank you.

```
function teste() {
                var db = commonDataBase.db;
                db.menu_tipo_usuario.where({id_tipo: "1"}).toArray(objeto => {
                    return Promise.all(objeto.map(item =>
                        Promise.all([
                            db.menu.get({id_menu: item.id_menu}),
                            db.menu_idioma.get({id_idioma: "pt-br", cod_menu: item.id_menu})
                        ]).then(result => {
                            // Set genre and albums as direct properties on each result
                            [item.menu, item.menu_idioma] = result;
                            return item;
                        })
                    ))
                }).then(function (menu_tipo_usuario) {
                    console.log(menu_tipo_usuario);
                });
            }

```
