### ISSUE TITLE
Using Observable addon resulting in strange unhandled rejection errors

### ISSUE THREAD

**Issue by AlmightyTritan** [dfahlander/Dexie.js#503]
Dexie has been working fine prior to adding the Observable addon and ever since I've been getting both these errors `Unhandled rejection: Error: Error: ` and `Unhandled rejection: TypeError: db._syncNodes.where(...).first is not a function`. The strange thing to me is I haven't created any queries against _syncNodes so I'm not to sure where they have originated from.

Here's the schema for my table
```
db.version(1).stores({
    games: '$$uuid, &gameId, &igdbId, &title, ttbAverageNormal, ttbMedianNormal,'
        + 'ttbShortestNormal, ttbLongestNormal, ttbEntriesNormal, gsCompleted,'
        + 'gsAbandoned, gsActive, gsBacklog, coverImage, screenshots, about,'
        + 'ttbAverageIGDB, offlineOnly, pendingDelete, version',
    records: '$$uuid, &recordId, gameId, completionStatus,'
        + 'offlineOnly, pendingDelete, version',
    sessions: '$$uuid, &sessionId, recordId, duration, date,'
        + 'offlineOnly, pendingDelete, version',
});
```

Here is the full stacks from the errors

```
Unhandled rejection: Error: Error: 
    at doReject (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3901:35)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1274:29)
    at IDBRequest.filter_record (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4043:42)
    at IDBRequest.eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:106:16)
From previous: 
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2854:40)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at Transaction._promise (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2853:18)
    at WriteableTable.getIDBObjectStore (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2266:53)
    at WriteableCollection._write (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3460:42)
    at WriteableCollection.modify (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3786:25)
    at Transaction.eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:905:141)
From previous: 
    at Function.resolve (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:921:16)
    at enterTransactionScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2169:29)
    at executePromiseTask (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1006:9)
    at new Promise (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:805:5)
    at Dexie._whenReady (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1854:16)
    at Dexie.transaction (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2165:105)
    at cleanup (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:898:19)
    at callListener (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1105:19)
From previous: 
    at Promise.then (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:813:18)
    at Promise.finally (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:847:21)
    at readChanges (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:828:19)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:879:13)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4475:20)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at Function.vip (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4473:16)
From previous: 
    at Promise.then (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:813:18)
    at readChanges (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:807:12)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:879:13)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4475:20)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at Function.vip (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4473:16)
    at poll (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:878:55)
From previous: 
    at Promise.then (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:813:18)
    at WriteableCollection._read (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3454:66)
    at WriteableCollection.toArray (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3554:29)
    at readChanges (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:788:91)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:879:13)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4475:20)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
From previous: 
    at Promise.then (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:813:18)
    at tempTransaction (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1832:16)
    at WriteableTable.getIDBObjectStore (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2266:99)
    at WriteableCollection._read (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3454:42)
    at WriteableCollection.toArray (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3554:29)
    at readChanges (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:788:91)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:879:13)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:4475:20)
From previous: 
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2854:40)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at Transaction._promise (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2853:18)
    at tempTransaction (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1826:26)
    at WriteableTable.getIDBObjectStore (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2266:99)
    at WriteableCollection._read (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3454:42)
    at WriteableCollection.toArray (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:3554:29)
defaultErrorHandler @ dexie.js?7f5c:1253
globalError @ dexie.js?7f5c:1351
(anonymous) @ dexie.js?7f5c:1206
finalizePhysicalTick @ dexie.js?7f5c:1205
callListener @ dexie.js?7f5c:1122
endMicroTickScope @ dexie.js?7f5c:1194
(anonymous) @ dexie.js?7f5c:1280
filter_record @ dexie.js?7f5c:4043
(anonymous) @ dexie.js?7f5c:106
```
```
Unhandled rejection: TypeError: db._syncNodes.where(...).first is not a function
    at Transaction.eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:854:58)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2195:49)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:982:17)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:968:20)
    at executePromiseTask (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1006:9)
    at new Promise (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:805:5)
    at Function.follow (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:967:16)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2193:36)
From previous: 
    at Function.follow (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:967:16)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2193:36)
    at usePSD (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1314:16)
    at newScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1301:14)
    at eval (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2170:24)
    at callListener (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1105:19)
    at endMicroTickScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1194:25)
    at Immediate.physicalTick (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1167:30)
From previous: 
    at Function.resolve (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:921:16)
    at enterTransactionScope (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2169:29)
    at executePromiseTask (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1006:9)
    at new Promise (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:805:5)
    at Dexie._whenReady (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:1854:16)
    at Dexie.transaction (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:1359:1), <anonymous>:2165:105)
    at heartbeat (eval at <anonymous> (E:\Tristan\Developement\Wrapdit\Desktop\app\dist\build.js:2129:1), <anonymous>:853:12)
defaultErrorHandler	@	dexie.js?7f5c:1253
globalError	@	dexie.js?7f5c:1351
(anonymous)	@	dexie.js?7f5c:1206
finalizePhysicalTick	@	dexie.js?7f5c:1205
callListener	@	dexie.js?7f5c:1122
endMicroTickScope	@	dexie.js?7f5c:1194
physicalTick	@	dexie.js?7f5c:1167
runCallback	@	timers.js:651
tryOnImmediate	@	timers.js:624
processImmediate	@	timers.js:596
```

**Comment by westernmonster** [comment]
got the same error.

**Comment by dfahlander** [comment]
dexie-observable depends on dexie@2.0.0-beta. Check you are using a 2.0-version of Dexie.
