### ISSUE TITLE
Get tests running under Node.js with IndexedDBShim

### ISSUE THREAD

**Issue by aral** [dfahlander/Dexie.js#701]
It’s possible to run Dexie under Node using IndexedDBShim (https://github.com/dfahlander/Dexie.js/issues/359#issuecomment-390636035), however, we do not know for certain that it behaves as expected as the test suite currently only runs in the browser environment.

Given that IndexedDBShim currently has [some issues under Node](https://github.com/axemclion/IndexedDBShim/issues/296), it would be good to now whether and how it effects expected behaviour in Dexie.

@dfahlander Do you have any thoughts on a strategy to make the test suite isomorphic so that it can be run under both browsers and Node?

**Comment by aral** [comment]
Just a quick update that I’m working on this. Just a brief update:

Made some progress using [node-qunit](https://github.com/qunitjs/node-qunit) but that wasn’t picking up the async tests (it’s not actively maintained).

I just got the first batch of test (in tests-table.js) to run under Node using qunit-tap (after seeing [this comment](https://github.com/qunitjs/node-qunit/issues/110#issuecomment-172603925) by @leobalter – thanks, Leo.)

Currently, it’s a terrible hack (I was just trying to get it working) and I’ve hardcoded some browser-based globals that _dexie-unittest-utils.js_ was setting, etc. I also replaced the imports with requires to get it working.

Next step: going to try and make a test runner that doesn’t require any code changes on the existing tests. Will keep you updated on my progress and push a brach to my fork when I have something a bit more presentable.

PS. Currently, all tests in tests_table.js are passing under Node, except for test 5 (`not ok 5 - Transaction failed: ReferenceError: IDBKeyRange is not defined, expected: true, got: false, test: where, module: table`) and 17 (`not ok 17 - ReferenceError: IDBKeyRange is not defined, expected: true, got: false, test: put, module: table`). Will take a quick look into those also.

**Comment by dfahlander** [comment]
Thanks a lot for looking into this. The tests will definitely need to be converted to universal JS in one or other way. I just looked up the issue with IDBKeyRange, and found a few locations in WhereClause. Should be the only ones using it. It's now fixed in master.

**Comment by aral** [comment]
Awesome news on the IDBKeyRange issues. Going to start working on a very minimalist test runner for Node now: basically, my plan is to:

1. Update the tests themselves so any browser-specific  globals are conditionally applied or replaced with defaults that make sense for Node.
2. Concatenate all the tests into a single file.
3. Wrap it with qunit-tap and the IndexedDBShim and run them.

🤞

**Comment by dfahlander** [comment]
Thanks! Whatever method you choose to make it run on node, I'm extraordinary happy. Maybe rollup could be of some help with the bundling of all modules into a single CommonJS based one? Currently the test suite is bundled using rollup config in `tools/build-configs/rollup.tests.config.js`. Maybe just copy that one, remove the 'external' parts (QUnit and dexie) and mock them using using https://github.com/rollup/rollup-plugin-alias?

**Comment by aral** [comment]
@dfahlander When you’ve had a chance to look at the test results, can you please let me know what your thoughts are on the current state of Dexie on Node with IndexedDBShim. Do you see any major issues? (I will look through the results also but I’m, of course, not as familiar with the project as you are.) Would be great, once you have some time, to triage the fixes.

I hope the tests help and if there’s anything more I can do, please let me know. I’d really like to use this production on Indie Site unless you see major concerns/showstoppers :)

**Comment by dfahlander** [comment]
Yes, I will have a look as soon as possible. Please remind me if no feedback from me tomorrow.

**Comment by dfahlander** [comment]
Tried your branch but got `Error: Cannot find module 'websql/custom'`.

Repro:
```
npm install
npm test:node

# Preparing Dexie tests for Node.js.
# Preparing unit test utilities for use in Node.
# ########################################
# tests-table.js
# ########################################
module.js:538
    throw err;
    ^

Error: Cannot find module 'websql/custom'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at o (/Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:563)
    at /Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:754
    at Object.22../CFG (/Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:6712:15)
    at o (/Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:703)
    at /Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:754
    at Object.21../CFG (/Users/daw/repos/dexie2/node_modules/indexeddbshim/dist/indexeddbshim-node.js:6691:19)
{ Error: Exited with code 1
    at ChildProcess.child.child_process.fork.on (/Users/daw/repos/dexie2/node_modules/child-process-es6-promise/index.js:106:37)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) code: 1, stderr: '', stdout: '', signal: null }
...
```

**Comment by aral** [comment]
I wonder if that’s because I added IndexedDBShim as a dev dependency? Nuking my node_modules now and doing a fresh `npm install` to try and reproduce. Will update.

**Comment by aral** [comment]
Hmm, just nuked node_modules and did a fresh npm install. It’s not that… 🤔

**Comment by aral** [comment]
What Node version are you running? (grasping at straws here, but who knows…) I’m on v8.11.1 and npm version 6.0.1.

**Comment by dfahlander** [comment]
I'll try remove node_modules and retry...

**Comment by dfahlander** [comment]
Still issue but I'll upgrade node and npm... I'm also on mac high sierra.

**Comment by dfahlander** [comment]
Got it working!

# Analyse

* Sorting issues. Seems it does not order results on queried index. (
  table: 23,24,25, 104, 105
  collection: 10, 11, 13, 40, 
* QUnit patching error (notEqual (or deepEqual) not polyfilled) (table 114, 115, upgrading 25
* Times out instead of throwing when accessing a non-existing table (
  table 123, transaction 10, 12, 14, 
* Strange errors: collection 68, 70, 72, 74: str.replace is not a function.
* Charset incompatibility: collection 92 - 101.
* Unknown problems: collection 227. Maybe a lack of multientry support in IndexedDBShim.
* Creating multiple databases: open 18, 19, 20, 21, 
* Native async await not supported: transaction 12, 
* unhandledrejection event may not work as expected in node:
   exception-handling 1
   misc 12,13, 28, 29, 30
* General timeout instead of exceptions: exception-handling 6, 7, 8, 
* Issue #360 seems to be present: misc 18
* Blob compatibility: blob 1, 3. Blobs are DOM-specific and should not be used in node anyway. For supporting blobs in IndexedDBShim, it must be able to structure-clone it. Workaround: Use binary arrays instead (such as UInt8Array).

# Summary

Most operations goes fine. All basic normal stuff seems to work, but beware the following:

* Sorting seems not to work correctly with IndexedDBShim on node. That is, db.table.orderBy() is not useful, nor can you rely on the order of rows returned from a query.
* Error handling suffers from timing out instead of throwing for some operations. May be related to Dexie src using CustomEvent to trigger unhandled rejections. May be solved in Dexie src. Could possibly also be that IndexedDBShim would not handle errors as expected.
* Seems not to support certain unicode chars (collection test numbers 92 - 101 where we generate a string out of random characters).
* Seems to be issues working on multiple databases at the same time.
* Native async await not working (which is does not in Firefox either due to incompatiblity between IndexedDB and Promise). Transpiled async await still fine.
* unhandledrejection event not signalled as expected. Reason: We trigger the event via a CustomEvent which is DOM-specific. Could be solved in Dexie src.
* Use UInt8Array instead of Blob to support both node and browser.

**Comment by aral** [comment]
The [table and collection sorting/ordering-related issues](https://github.com/dfahlander/Dexie.js/issues/701#issuecomment-392756378) might be related to https://github.com/axemclion/IndexedDBShim/issues/296

**Comment by aral** [comment]
I’ve confirmed that the tests are, in fact, using Dexie.Promise and not native promises so based on what you wrote above, that’s not the issue.

**Comment by dfahlander** [comment]
I am suspecting a collation issue in the websql module maybe. IndexedDB assumes ordinal sort while it may be the case that sqlite defaults to another collation. Just a theory though.
