### ISSUE TITLE
Regression in 3.x: Dexie.delete() breaks on dexie@next in node.js

### ISSUE THREAD

**Issue by aral** [dfahlander/Dexie.js#703]
## To reproduce:

1. Setup project:

```bash
mkdir dexie-regression && cd dexie-regression && npm init -y && npm i dexie && npm i indexeddbshim && touch index.js
```

2. Confirm that the following works in Dexie 2.0.4 (`node index.js`):

```javascript
const Dexie = require('dexie')

// Node.js IndexedDB shim
if (typeof window === 'undefined') {
  const setGlobalVars = require('indexeddbshim')
  const shim = {}
  setGlobalVars(shim, {checkOrigin: false})
  const { indexedDB, IDBKeyRange } = shim

  Dexie.dependencies.indexedDB = indexedDB
  Dexie.dependencies.IDBKeyRange = IDBKeyRange
}

async function start () {
  // Uncomment to resolve error under dexie@next
  await Dexie.delete('tasks')

  const db = new Dexie('tasks')
  db.version(1).stores({
    tasks: '++id,date,description,done'
  })

  // This works
  await db.tasks.put({ date: new Date(), description: `Additional insert`, done: 0 })
}

start()
```

3. Upgrade to dexie@next: `npm i dexie@next`
4. Run `node index.js` again

## What should happen

It should work.

## What actually happens

Error:

```bash
(node:40296) UnhandledPromiseRejectionWarning: ReferenceError: indexedDB is not defined
    at doDelete (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:3573:27)
    at /Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:3587:17
    at executePromiseTask (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:796:9)
    at new Promise$1 (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:639:5)
    at Dexie.delete (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:3570:16)
    at Function.delete (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/node_modules/dexie/dist/dexie.js:3690:25)
    at start (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/index.js:63:21)
    at Object.<anonymous> (/Users/aral/indie/net/meta/spikes/databases/dexie-isomorphic/index.js:128:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:40296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aral** [comment]
Actually, I don’t think the issue is with `npm link` at all but a change in _package.json_ between 2.0.4 and master:

## package.json in 2.0.4

```json
{
  "name": "dexie",
  "version": "2.0.4",
  "description": "A Minimalistic Wrapper for IndexedDB",
  "main": "dist/dexie.js",
  "module": "dist/dexie.es.js",
  "jsnext:main": "dist/dexie.es.js",
  "typings": "dist/dexie.d.ts",
  "jspm": {
    "format": "cjs",
    "ignore": [
      "src/"
    ]
  },
…
```

## package.json in master:

```json
{
  "name": "dexie",
  "version": "3.0.0-alpha.2",
  "description": "A Minimalistic Wrapper for IndexedDB",
  "main": "dist/dexie.js",
  "module": "dist/dexie.mjs",
  "jsnext:main": "dist/dexie.mjs",
  "typings": "dist/dexie.d.ts",
  "jspm": {
    "format": "cjs",
    "ignore": [
      "src/"
    ]
  },
…
```
