### ISSUE TITLE
Node tests: random failures on tests-collection test “or-issue#15-test” (assertions 100-109)

### ISSUE THREAD

**Issue by aral** [dfahlander/Dexie.js#711]
The _or-issue#15-test_ in the tests-collection tests randomly fails.

## To reproduce

Run the following command several times until you see the error. It is “random” – so on some runs, all tests will pass.

```bash
npm run test:node -- tests-collection
```

## Failures:

```bash
not ok 100 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 101 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 102 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 103 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 104 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 105 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 106 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 107 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 108 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
not ok 109 - error:SyntaxError: Unexpected token  in JSON at position 25
#     at JSON.parse (<anonymous>)
#     at Typeson.s.parse (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:776:2369)
#     at Object.decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:6617:20)
#     at IDBCursorWithValue.IDBCursor.__decode (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1789:35)
#     at Object.cursorContinue [as op] (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1845:20)
#     at executeNextRequest (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5237:23)
#     at success (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:5173:13)
#     at /Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1767:13
#     at triggerSuccess (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1839:36)
#     at checkKey (/Users/aral/indie/other/forks/IndexedDBShim/dist/indexeddbshim-node.js:1849:29), expected: true, got: false, test: or-issue#15-test, module: collection, source: at /Users/aral/indie/other/forks/dexie/node_modules/qunitjs/qunit/qunit.js:2194:12
```

**Comment by aral** [comment]
This is a test runner timeout related issue with test __or-issue#15-test__.

The errors that we’re seeing occur when the QUnit test timeout is hit. I had this at 3000ms. Raising the per-test timeout to 5000ms has all tests passing in tests-collection.js.

**Comment by aral** [comment]
OK, no, that’s not it. This is a random error.

I just raised the per test timeout to 10 seconds and the main test runner timeout to 30 seconds and I can reproduce the “Unexpected token in JSON at position 25" error, above, on some runs but not others.

This looks like a hairy one.

**Comment by dfahlander** [comment]
It may literally a random one: or-issue#15-test populates the DB with random strings generated like this:

```js
    db.on('populate', function () {
        ok(true, "on(populate) called");
        for (var i = 0; i < 100; ++i) {
            db.phones.add({ id: 3 + i, name: "Name" + randomString(16), additionalFeatures: [randomString(10)], android: 1, availability: 0, battery: 1, camera: 1 });
        }

        function randomString(count) {
            var ms = [];
            for (var i = 0; i < count; ++i) {
                ms.push(String.fromCharCode(32 + Math.floor(Math.random() * 96)));
            }
            return ms.join('');
        }
    });
```
Maybe the IndexedDBShim without the unicode support, bails out after this has happened.

**Comment by dfahlander** [comment]
But the chars are in ascii 32-96 so shouldn't be issue actually. I might be wrong here.

**Comment by dfahlander** [comment]
Oh, it is chars [32..127] and it could be char 127 (DEL) that makes the shim unhappy. Trying now to change from 96 to 95 to avoid that special char. Then the strings will only contain basic ascii chars.

**Comment by dfahlander** [comment]
Closing this particular issue as the randomness was solved after avoiding char 127 in the set of random strings generated in or-issue#15-test.

**Comment by aral** [comment]
@dfahlander Hmm, afaik, IndexedDBShim should handle Unicode correctly (and if it doesn’t, that’s a bug). I’m not sure if “fixing” the test here actually hides the core issue. @brettz9: thoughts?

**Comment by brettz9** [comment]
Yes, it should handle any string correctly, even unpaired surrogates. If there is a problem, I suspect the underlying SQLite might not like some control character or other, in which case, we probably just need to add to one or more of our escaping functions in utilities.

**Comment by dfahlander** [comment]
Think it is closed from the dexie point of view. This could be opened in IndexedDBShim. A narrowed down repro would probably do:

```js
store.put({id: 1, str: String.fromCharCode(127)})
```

**Comment by brettz9** [comment]
Yeah, but I didn't find a single problem on my end running through all code units or code points, at least not with a single number supplied to `String.fromCharCode` (0 - 0xFFFF) or `String.fromCodePoint` (0 - 0x10FFFF)...

Running Node 9.2.1... Test at https://github.com/brettz9/IndexedDBShim/blob/code-unit-code-point-tests/tests-mocha/IDBObjectStore/put-spec-chars.js

**Comment by dfahlander** [comment]
I see. Maybe the property need be indexed to trigger the issue. If not there must be something else. Don't know if we're using the unicode version of the shim or not in our tests.

**Comment by brettz9** [comment]
Looks like from the error messages above, the file is `indexeddbshim-node.js` which would not be including the Unicode support. It should be using `indexeddbshim-UnicodeIdentifiers-node.js`...

**Comment by aral** [comment]
@brettz9 Ah, my bad. I’ll fix that, thank you @brettz9. @dfahlander will you revert the test (or shall I?) It’s good to have the Unicode characters in there (or to create a new test specifically for that – happy to do it) so that we cover that use case. Dexie should be Unicode compliant by default.

**Comment by dfahlander** [comment]
Let's see if that was the issue. I thought the unicode module regards to index- and table names only. This was an issue with the data. The particular test that I modified was not testing unicode support, but we could easily add a new unicode test.

**Comment by aral** [comment]
(Re: Unicode support: Yeah, I was confused for the same reasons when I read the IndexedDBShim docs.)
