### ISSUE TITLE
TransactionInactiveError if UUID is used in angular

### ISSUE THREAD

**Issue by ramasa** [dfahlander/Dexie.js#726]
todos: '++id,title', is working but
  todos: '$$oid,title' is failing with TransactionInactiveError 

**console output**
```
Unhandled rejection: add/<@http://192.168.1.13:8080/vendor.js:123366:70
supplyIdbStore@http://192.168.1.13:8080/vendor.js:123040:24
tempTransaction/</<@http://192.168.1.13:8080/vendor.js:122545:28
usePSD@http://192.168.1.13:8080/vendor.js:122028:16
newScope@http://192.168.1.13:8080/vendor.js:121925:14
tempTransaction/<@http://192.168.1.13:8080/vendor.js:122543:24
_promise/p<@http://192.168.1.13:8080/vendor.js:123632:30
executePromiseTask@http://192.168.1.13:8080/vendor.js:121632:9
Promise@http://192.168.1.13:8080/vendor.js:121449:5
_promise@http://192.168.1.13:8080/vendor.js:123631:25
tempTransaction@http://192.168.1.13:8080/vendor.js:122542:20
getTransaction@http://192.168.1.13:8080/vendor.js:123033:17
getIDBObjectStore@http://192.168.1.13:8080/vendor.js:123042:20
add@http://192.168.1.13:8080/vendor.js:123353:20
./src/app/app.component.ts/AppComponent.prototype.test@http://192.168.1.13:8080/main.js:133:9
View_AppComponent_0/<@ng:///AppModule/AppComponent.ngfactory.js:15:23
handleEvent@http://192.168.1.13:8080/vendor.js:62251:16
callWithDebugContext@http://192.168.1.13:8080/vendor.js:63344:22
debugHandleEvent@http://192.168.1.13:8080/vendor.js:63047:12
dispatchEvent@http://192.168.1.13:8080/vendor.js:59710:16
renderEventHandlerClosure/<@http://192.168.1.13:8080/vendor.js:60154:38
decoratePreventDefault/<@http://192.168.1.13:8080/vendor.js:111838:36
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://192.168.1.13:8080/polyfills.js:2743:17
onInvokeTask@http://192.168.1.13:8080/vendor.js:55949:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://192.168.1.13:8080/polyfills.js:2742:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://192.168.1.13:8080/polyfills.js:2510:28
./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://192.168.1.13:8080/polyfills.js:2818:24
invokeTask@http://192.168.1.13:8080/polyfills.js:3862:9
globalZoneAwareCallback@http://192.168.1.13:8080/polyfills.js:3888:17
```

**Browser javascript debug is showing**
```
filename: "http://192.168.1.13:8080/vendor.js"
lineNumber: 123366
message: "A request was placed against a transaction which is currently not active, or which is finished."
name: "TransactionInactiveError"
```

Dependency
    "@angular/core": "^6.0.3",
    "dexie": "^2.0.4",
    "dexie-observable": "^1.0.0-beta.4",
    "dexie-syncable": "^1.0.0-beta.4",

```
import Dexie from 'dexie';
import 'dexie-observable';
import 'dexie-syncable';
export class DexieService extends Dexie {
  constructor() { 
    super('ram');
    this.version(1).stores({
      todos: '$$oid,title',
    });
```

```
class Todo { 
  oid?: string;
  title: string;
  done: boolean;
}
export class AppComponent {
  //table: Dexie.Table<Todo, number>;
  table: Dexie.Table<Todo, string>;
  constructor(private dexieService: DexieService){
    this.table = this.dexieService.table('todos');
  }
  test(){
    var data={title:'Test222',done:false};
    this.table.add(data);
  }
```

**Comment by dfahlander** [comment]
Could it be that you've already created the db with take "todos" using ++id as primary key. Try rename or delete the db. Same error? Also what error do you receive if catching the call to table.add()?

**Comment by ramasa** [comment]
I used to delete database each time before testing.
Anyhow this time changed db to txn and added catch.
Got little different error in Chrome than Firefox
Chrome
```
dexie.es.js:1379 Unhandled rejection: DataError: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
Error: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at http://localhost:4200/vendor.js:123570:79
    at supplyIdbStore (http://localhost:4200/vendor.js:123244:24)
    at http://localhost:4200/vendor.js:122749:28
    at usePSD (http://localhost:4200/vendor.js:122232:16)
    at newScope (http://localhost:4200/vendor.js:122129:14)
    at http://localhost:4200/vendor.js:122747:24
    at http://localhost:4200/vendor.js:123836:30
    at executePromiseTask (http://localhost:4200/vendor.js:121836:9)
    at new Promise (http://localhost:4200/vendor.js:121653:5)
    at Transaction._promise (http://localhost:4200/vendor.js:123835:25)
From previous: 
    at Transaction._promise (http://localhost:4200/vendor.js:123835:25)
    at tempTransaction (http://localhost:4200/vendor.js:122746:26)
    at http://localhost:4200/vendor.js:122736:61
    at http://localhost:4200/vendor.js:122251:23
    at callListener (http://localhost:4200/vendor.js:121934:19)
    at endMicroTickScope (http://localhost:4200/vendor.js:122021:25)
    at IDBTransaction.__zone_symbol__ON_PROPERTYcomplete (http://localhost:4200/vendor.js:122088:17)
    at IDBTransaction.wrapFn (http://localhost:4200/polyfills.js:3510:39)
```
Firefox
```
Unhandled rejection: DataError: Data provided to an operation does not meet requirements.
add/<@http://localhost:4200/vendor.js:123570:70
supplyIdbStore@http://localhost:4200/vendor.js:123244:24
tempTransaction/</<@http://localhost:4200/vendor.js:122749:28
usePSD@http://localhost:4200/vendor.js:122232:16
newScope@http://localhost:4200/vendor.js:122129:14
tempTransaction/<@http://localhost:4200/vendor.js:122747:24
_promise/p<@http://localhost:4200/vendor.js:123836:30
executePromiseTask@http://localhost:4200/vendor.js:121836:9
Promise@http://localhost:4200/vendor.js:121653:5
_promise@http://localhost:4200/vendor.js:123835:25
tempTransaction@http://localhost:4200/vendor.js:122746:20
tempTransaction/<@http://localhost:4200/vendor.js:122736:61
nativeAwaitCompatibleWrap/<@http://localhost:4200/vendor.js:122251:20
callListener@http://localhost:4200/vendor.js:121934:19
endMicroTickScope@http://localhost:4200/vendor.js:122021:17
wrap/<@http://localhost:4200/vendor.js:122088:17
wrapFn@http://localhost:4200/polyfills.js:3510:30
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2743:17
onInvokeTask@http://localhost:4200/vendor.js:55949:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2742:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:2510:28
./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:4200/polyfills.js:2818:24
invokeTask@http://localhost:4200/polyfills.js:3862:9
globalZoneAwareCallback@http://localhost:4200/polyfills.js:3888:17

From previous: 
_promise@http://localhost:4200/vendor.js:123835:25
tempTransaction@http://localhost:4200/vendor.js:122746:20
tempTransaction/<@http://localhost:4200/vendor.js:122736:61
nativeAwaitCompatibleWrap/<@http://localhost:4200/vendor.js:122251:20
callListener@http://localhost:4200/vendor.js:121934:19
endMicroTickScope@http://localhost:4200/vendor.js:122021:17
wrap/<@http://localhost:4200/vendor.js:122088:17
wrapFn@http://localhost:4200/polyfills.js:3510:30
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2743:17
onInvokeTask@http://localhost:4200/vendor.js:55949:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2742:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:2510:28
./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:4200/polyfills.js:2818:24
invokeTask@http://localhost:4200/polyfills.js:3862:9
globalZoneAwareCallback@http://localhost:4200/polyfills.js:3888:17
dexie.es.js:1379

```

**Comment by dfahlander** [comment]
Seems the addons are not active. It could be the unnamed imports that doesnt do their job in the webpack setup (just a theory). Try explicitly provide the addons to Dexie constructor :

```ts
import Dexie from 'dexie';
import observable from 'dexie-observable';
import syncable from 'dexie-syncable';

export class DexieService extends Dexie {
  constructor() { 
    super('ram', {addons: [observable, syncable]});
    this.version(1).stores({
      todos: '$$oid,title',
    });
  } 
} 
```

**Comment by ramasa** [comment]
Created new angular project with your suggestion, still getting same error
New code below

```
import { Injectable } from '@angular/core';
import Dexie from 'dexie';

import 'dexie-observable';
import 'dexie-syncable';


interface Friend {
  id?: string;
  name?: string;
  age?: number;
}

@Injectable({
  providedIn: 'root'
})
export class DexieService extends Dexie {
  public friends!: Dexie.Table<Friend, string>;

  constructor() {
    super("FriendDatabase", { addons: [Dexie.Observable, Dexie.Syncable] });
    this.version(1).stores({
      friends: "$$id,name,age"
    });
  }

  add() {
    var item = { name: 'ram', age: 20 };
    try {
      this.friends.add(item);
    } catch (e) {
      console.log(e);
    }
  }
}
```

**Comment by dfahlander** [comment]
The new sample still does the same type of import as before:

```js
import 'dexie-observable';
import 'dexie-syncable';
```

Try if naming the default imports helps:

```js
import observable from 'dexie-observable';
import syncable from 'dexie-syncable';

...

export class DexieService extends Dexie {
  ...
  constructor() {
    super("FriendDatabase", { addons: [observable, syncable] });
    ...
  }
}

```

**Comment by ramasa** [comment]
Sorry, missed that.
Now updated [code](https://github.com/ramasa/dexietest/blob/master/src/app/dexie.service.ts), cleared db, retested ,but getting same error

```
dexie.es.js:1379 Unhandled rejection: DataError: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
Error: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at http://localhost:4200/vendor.js:53748:79
    at supplyIdbStore (http://localhost:4200/vendor.js:53422:24)
```

**Comment by dfahlander** [comment]
Ok, then we'll have to check why dexie-observable doesn't respect the $$ prefix. Until solved, try generating an UUID manually. There's a helper function for that in [Dexie.Observable.createUUID()](http://dexie.org/docs/Observable/Dexie.Observable#dexieobservablecreateuuid)

**Comment by nleco** [comment]
it seems I had to install and import this.

```
import 'dexie-syncable';
```

I thought I read
