### ISSUE TITLE
Failed to execute 'add' on 'IDBObjectStore'

### ISSUE THREAD

**Issue by adnathanail** [dfahlander/Dexie.js#737]
# Code
## dexie.service.ts
```typescript
import Dexie from 'dexie';
import { IJourney, Journey } from '../models/journey.model';

export class DexieService extends Dexie {
  journey: Dexie.Table<IJourney, number>;
  constructor() {
    super('driver-app');
    const db = this;
    db.version(1).stores({
      journey: 'id,date,capacity,route,loc',
    });
    db.journey.mapToClass(Journey);
    db.journey.add(new Journey(1, new Date(), 2, 3, 4));
  }
}
```
## journey.model.ts
```typescript
export interface IJourney {
  id: number;
  date: Date;
  capacity: number;
  route: number;
  loc: number;
}
export class Journey implements IJourney {
  id: number;
  date: Date;
  capacity: number;
  route: number;
  loc: number;
  constructor(id: number, date: Date, capacity: number, route: number, loc: number) {}
}
```
# Description
The above code is part of an angular app run with DexieService provided in 'app.module.ts' and being in the constructor of a view.
## Versions
- Angular 6.1.2
- Dexie 2.0.4
## Problem
I get the following error message, as a result of the `db.journey.add(new Journey(1, new Date(), 2, 3, 4));`:
```
Unhandled rejection: DataError: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
Error: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at http://localhost:4200/vendor.js:134044:79
    at supplyIdbStore (http://localhost:4200/vendor.js:133718:24)
    at http://localhost:4200/vendor.js:133223:28
    at usePSD (http://localhost:4200/vendor.js:132706:16)
    at newScope (http://localhost:4200/vendor.js:132603:14)
    at http://localhost:4200/vendor.js:133221:24
    at http://localhost:4200/vendor.js:134310:30
    at executePromiseTask (http://localhost:4200/vendor.js:132310:9)
    at new Promise (http://localhost:4200/vendor.js:132127:5)
    at Transaction._promise (http://localhost:4200/vendor.js:134309:25)
From previous: 
    at Transaction._promise (http://localhost:4200/vendor.js:134309:25)
    at tempTransaction (http://localhost:4200/vendor.js:133220:26)
    at http://localhost:4200/vendor.js:133210:61
    at http://localhost:4200/vendor.js:132725:23
    at callListener (http://localhost:4200/vendor.js:132408:19)
    at endMicroTickScope (http://localhost:4200/vendor.js:132495:25)
    at IDBOpenDBRequest.__zone_symbol__ON_PROPERTYsuccess (http://localhost:4200/vendor.js:132562:17)
    at IDBOpenDBRequest.wrapFn (http://localhost:4200/polyfills.js:3510:39)
```
My primary key is "inbound" as it says in the docs about bulk add [here](http://dexie.org/docs/Table/Table.bulkAdd()). When I tried including a key I get this different error implying I was right about not providing the key:
```
Unhandled rejection: DataError: Failed to execute 'add' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.
Error: Failed to execute 'add' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.
    at http://localhost:4200/vendor.js:134044:54
    at supplyIdbStore (http://localhost:4200/vendor.js:133718:24)
    at http://localhost:4200/vendor.js:133223:28
    at usePSD (http://localhost:4200/vendor.js:132706:16)
    at newScope (http://localhost:4200/vendor.js:132603:14)
    at http://localhost:4200/vendor.js:133221:24
    at http://localhost:4200/vendor.js:134310:30
    at executePromiseTask (http://localhost:4200/vendor.js:132310:9)
    at new Promise (http://localhost:4200/vendor.js:132127:5)
    at Transaction._promise (http://localhost:4200/vendor.js:134309:25)
From previous: 
    at Transaction._promise (http://localhost:4200/vendor.js:134309:25)
    at tempTransaction (http://localhost:4200/vendor.js:133220:26)
    at http://localhost:4200/vendor.js:133210:61
    at http://localhost:4200/vendor.js:132725:23
    at callListener (http://localhost:4200/vendor.js:132408:19)
    at endMicroTickScope (http://localhost:4200/vendor.js:132495:25)
    at IDBOpenDBRequest.__zone_symbol__ON_PROPERTYsuccess (http://localhost:4200/vendor.js:132562:17)
    at IDBOpenDBRequest.wrapFn (http://localhost:4200/polyfills.js:3510:39)
```
This is almost certainly me being an idiot, but if you could help me anyway I would be eternally greatful!

**Comment by dfahlander** [comment]
Seems the constructor does not set any property. So basically you are adding an empty object.

**Comment by adnathanail** [comment]
Oh my god I'm so sorry for wasting your time. It's typescript and I thought it could automatically do the assignment but it turns out I need a public or private keyword ([relevant article](https://kendaleiv.com/typescript-constructor-assignment-public-and-private-keywords/)).
## journey.model.ts
```typescript
export interface IJourney {
  id: number;
  date: Date;
  capacity: number;
  route: number;
  loc: number;
}
export class Journey implements IJourney {
  constructor(
    public id: number,
    public date: Date,
    public capacity: number,
    public route: number,
    public loc: number
  ) {}
}
```
