### ISSUE TITLE
ModifyError with 3.0.0-alpha.5

### ISSUE THREAD

**Issue by dpogue** [dfahlander/Dexie.js#762]
Started getting this ModifyError in certain spots in our app after updating to Dexie 3.0.0-alpha.5:

```
Error: Error modifying one or more objects. Errors: function () {
    return Promise.all(this);
}
    at http://localhost:9876/base/webpack.tests.js:66580:31
    at http://localhost:9876/base/webpack.tests.js:65722:23
    at callListener (http://localhost:9876/base/webpack.tests.js:65456:19)
    at endMicroTickScope (http://localhost:9876/base/webpack.tests.js:65528:25)
    at http://localhost:9876/base/webpack.tests.js:65587:17
    at FDBRequest.done [as onsuccess] (http://localhost:9876/base/webpack.tests.js:67444:21)
    at invokeEventListeners (http://localhost:9876/base/webpack.tests.js:73789:31)
    at FDBRequest../node_modules/fake-indexeddb/build/lib/FakeEventTarget.js.FakeEventTarget.dispatchEvent (http://localhost:9876/base/webpack.tests.js:73842:13)
From previous: 
    at Promise$1.then (http://localhost:9876/base/webpack.tests.js:65223:22)
    at http://localhost:9876/base/webpack.tests.js:66578:37
    at http://localhost:9876/base/webpack.tests.js:65722:23
    at callListener (http://localhost:9876/base/webpack.tests.js:65456:19)
    at endMicroTickScope (http://localhost:9876/base/webpack.tests.js:65528:25)
    at http://localhost:9876/base/webpack.tests.js:65587:17
    at FDBRequest.req.onsuccess (http://localhost:9876/base/webpack.tests.js:67556:67)
    at invokeEventListeners (http://localhost:9876/base/webpack.tests.js:73789:31)
From previous: 
    at Promise$1.then (http://localhost:9876/base/webpack.tests.js:65223:22)
    at nextChunk (http://localhost:9876/base/webpack.tests.js:66536:109)
    at http://localhost:9876/base/webpack.tests.js:66578:24
    at http://localhost:9876/base/webpack.tests.js:65722:23
    at callListener (http://localhost:9876/base/webpack.tests.js:65456:19)
    at endMicroTickScope (http://localhost:9876/base/webpack.tests.js:65528:25)
    at http://localhost:9876/base/webpack.tests.js:65587:17
    at FDBRequest.req.onsuccess (http://localhost:9876/base/webpack.tests.js:67556:67)
From previous: 
    at Object.getMany (http://localhost:9876/base/webpack.tests.js:67585:24)
    at nextChunk (http://localhost:9876/base/webpack.tests.js:66536:38)
    at http://localhost:9876/base/webpack.tests.js:66578:24
    at http://localhost:9876/base/webpack.tests.js:65722:23
    at callListener (http://localhost:9876/base/webpack.tests.js:65456:19)
    at endMicroTickScope (http://localhost:9876/base/webpack.tests.js:65528:25)
    at http://localhost:9876/base/webpack.tests.js:65587:17
    at FDBRequest.req.onsuccess (http://localhost:9876/base/webpack.tests.js:67556:67)"
```

It's reproducible in our test suite (which is using FakeIndexedDB, hence the FDB stuff above), but I've also seen it in Chrome when running the app with real indexedDB.

This error seems to happen in a spot when we are calling `this.$db.update(id, data)`.  
There is another spot in the app where we call `this.$db.put(data)` and it seems to work with no problem.

I can try to dig in a bit deeper and provide more information if you let me know what would be useful.

**Comment by dfahlander** [comment]
Thanks for this report! Table.update() and Collection.modify() is totally rewritten to not use IDBCursor.update() but instead use IDBObjectStore.put().

If you have the possibility to run it when chrome developer tools is open with "pause on caught exception" turned on, to find where the exception or error event happens. Even if it is an error event, it is interseting what type of event it is. If it for example is a ConstraintError, it would be nice to re-run the code putting some console.log() in various places of Collection.modify() to see what is beeing send down to DBCore in the mutate() request.

(It is also strange that the errors property contains a function. That could be a clue for me so far, but that is probably another issue.)

**Comment by dpogue** [comment]
Ahhhh, okay, setting breakpoints in Collection.modify() where it adds to the failures array allowed me to figure out what was going on.

There's a `for (let pos in failures)` loop in there that was looping over the empty array of failures. However, we'd added an `awaitPromises` method on `Array.prototype` that was getting picked up by that loop and being treated as a failure.

So the current fix for us is to make our `awaitPromises` hack non-enumerable, so it doesn't get picked up by the for...in loop, but it might be worth a check whether a standard for loop would be better here?
