### ISSUE TITLE
[Contribution] Typescript Stackblitz Demo

### ISSUE THREAD

**Issue by oleersoy** [dfahlander/Dexie.js#818]
I took the typescript repository demo and created a Stackblitz out of it.  Thought perhaps it could be used to complement the documentation.

https://stackblitz.com/edit/typescript-dexie-appdemo?file=index.ts

**Comment by dfahlander** [comment]
Thanks! Much apprechiated. I'll link to it from the docs!

**Comment by MVSICA-FICTA** [comment]
Thanks for this more up to date demo! I was just working to get Dexie samples up using the Parcel Bundler. Looking high and low at the samples provided they look a little aged and so far I have yet to make some Dexie sample work with Parcel. Feeling the pinch between the most basic HTML demo and the cutting edge Typescript demo that runs in the cloud but no where else right now.

Eager to get going, I downloaded this new stackblitz demo so I can try it locally. Figured it might be a good idea so I installed `npm install -S tslib @types/events` and created a tsconfig.json.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "ESNext",
    "lib": ["dom", "es2015", "es2015.collection"],
    "importHelpers": true,
    "strict": true,
    "moduleResolution": "node"
  }
}
```

All I got was the following error, not sure what it means since I am not into TypeScript a bunch:

```
parcel index.html
Server running at http://localhost:1234 
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "typescript" under a package
npm ERR! also called "typescript". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/star/.npm/_logs/2019-03-30T02_00_18_274Z-debug.log
�  /mnt/c/Users/thoma/codebase/applica-iobase/code-dexieIDB/dexie-appdemo-ts/index.ts: Failed to i
nstall typescript.
    at PromiseQueue.install [as process] (/home/star/.nvm/versions/node/v11.3.0/lib/node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

It would be great if a few more basic to more elaborate straight JavaScript and then also TypeScript samples could be added. Parcel is now a thing so once I get that working the Dexie API can open up to me :)

**Comment by oleersoy** [comment]
@MVSICA-FICTA I have a few repositories that are pure typescript and compile to ES5 modules.  For example:
https://github.com/fireflysemantics/is

I would think that you could take the typescript configuration / compiler settings and compile your Dexie project into an ES5 module.  Then depend on that project in your application and use parcel to trim anything you are not using.

The compile process generates an ES5 module with a Typescript typings file so it can be used in ES5 and Typescript environments.

If you have an MVCE posted to github I could take a look at it with you.

**Comment by MVSICA-FICTA** [comment]
@oleersoy I had a issue there after a long day I guess. Found out that Parcel has zero-config TS support so the tsconfig.json and extra TS package I was assuming were required were not after all. It turns out that after downloading your demo files, I just do a parcel index.html (or alternatively via script) and it runs just fine.

Best and thanks for the great demo!

**Comment by oleersoy** [comment]
Parcel is good stuff!
